{
  'env': { 'browser': true, 'es6': true, 'node': true },
  'parser': '@typescript-eslint/parser',
  'extends':
    [
      'react-app',
      'plugin:prettier/recommended',
      'plugin:react/recommended',
      'plugin:@typescript-eslint/eslint-recommended'
    ],
  'plugins': ['react', 'react-hooks', 'prettier', '@typescript-eslint'],
  'parserOptions':
    {
      'ecmaFeatures': { 'jsx': true },
      'ecmaVersion': 2018,
      'sourceType': 'module'
    },
  'rules':
    {
      'prettier/prettier': 'error',
      'react/prop-types': 0,
      'react/display-name': 0
    },
  'settings': { 'react': { 'version': 'detect' } },
  'globals': { 'Atomics': 'readonly', 'SharedArrayBuffer': 'readonly' }
}
