title: Crossfeed
description: Crossfeed

# GitHub information
# This is used for adding an edit this page link to the footer
github_info:
  organization: cisagov
  repository: crossfeed
  default_branch: master

# site_width: wide

theme: uswds-jekyll

sass:
  style: compressed

highlighter: rouge

minify_html: false

exclude:
  - _site
  - .bundle-cache
  - .jekyll-cache
  - .sass-cache
