source "https://rubygems.org"

gem "jekyll", "~> 4"

gem 'uswds-jekyll', '5.0.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

